apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: agrotrack-frontend
data:
  REACT_APP_API_URL: "http://185.193.66.50:31247/api"
  # This will be overridden by pipeline variables if needed
