apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: agrotrack-frontend
  labels:
    app: olive-lifecycle-frontend
spec:
  type: NodePort
  selector:
    app: olive-lifecycle-frontend
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
    # nodePort will be auto-assigned by Kubernetes (range 30000-32767)
